// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rffdonbbreyqzkurgrkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmZmRvbmJicmV5cXprdXJncmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTkyODQsImV4cCI6MjA2ODM5NTI4NH0.ThA95m6EBeNkqNpRd9mgto28y9wYV3t1kS84Tc69GCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});